name: Copy Issue on ODA Label Added

on:
  issues:
    types: [labeled]

jobs:
  copy-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the label is added
      if: github.event.action == 'labeled'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const payload = context.payload;
          if (payload.issue.labels.some(label => label.name === 'ODA')) {
            console.log('An issue has been labeled ODA. Copying the issue to the Open Documentation Academy repository.');
            const issueNumber = payload.issue.number;
            const repoOwner = payload.repository.owner.login;
            const repoName = payload.repository.name;
            const targetRepoOwner = 'minaelee';
            const targetRepoName = 'test-workflows';
            
            const issue = await github.rest.issues.get({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber
            });
            
            const issueTitle = issue.data.title;
            const issueBody = issueDetails.data.body + '\n\n---\n\nCopied from: [' + payload.repository.full_name + '#' + issueNumber + '](' + issue.html_url + ')';
            await github.rest.issues.create({
              owner: targetRepoOwner,
              repo: targetRepoName,
              title: issueTitle,
              body: issueBody
            });
          }
