name: Copy ODA-labeled Issues

on:
  issues:
    types: [labeled]

jobs:
  copy-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label is ODA
        if: ${{ github.event.label.name == 'ODA' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const targetRepoOwner = 'minaelee';
            const targetRepoName = 'test-workflows';   

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const issue = await octokit.rest.issues.get({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber
            });

            const issueTitle = issue.data.title;
            const issueBody = issue.data.body;

            await octokit.rest.issues.create({
              owner: targetRepoOwner,
              repo: targetRepoName,
              title: issueTitle,
              body: issueBody
            });
