name: Copy Issue on ODA Label Added

on:
  issues:
    types:
      - labeled

jobs:
  copy-issue:
    if: github.event.label.name == 'ODA'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/minaelee/test-workflows2/issues \
            -d '{"title":"test","body":"test"}'

        # This code sample is from https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api
        #   curl --request POST \
        #   --url https://api.github.com/repos/minaelee/test-workflows2/issues \
        #   --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        #   --header 'content-type: application/json' \
        #   --data '{
        #     "title": "test",
        #     "body": "This issue was automatically created by the GitHub Action workflow."
        #     }' \
        #   --fail
              
          # --url https://api.github.com/repos/canonical/open-documentation-academy/issues \

    # steps:
    #   - name: Copy issue to Open Documentation Academy repository
    #     uses: actions/github-script@v7
    #     with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       script: |
    #         console.log('An issue has been labeled ODA. Copying the issue to the Open Documentation Academy repository.');
    #         const issue = context.payload.issue;
    #         const originRepo = context.payload.repository;

    #         const originalIssueUrl = originRepo.html_url + '/issues/' + issue.number;
    #         const copiedIssueBody = issue.body + '\n\n---\n\nCopied from: [' + originRepo.full_name + '#' + issue.number + '](' + originalIssueUrl + ')';

    #         await github.rest.issues.create({
    #           owner: 'canonical',
    #           repo: 'open-documentation-academy',
    #           title: issue.title,
    #           body: copiedIssueBody
    #         });
